Importing the dependencies

In [1]:
#importing the libraries
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import csv

Data collection and Data pre-processing

In [4]:
#uploading the CSV file's contents to the added data frame
movies_data = pd.read_csv('/content/movies.csv')

In [5]:
#printing a data frames's five rows
movies_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [6]:
#to determine the data frame's rows and columns counts
movies_data.shape

(4803, 24)

In [7]:
#choosing the right features to suggest
selected_features = ['genres','keywords','original_language','tagline','cast','director',]
print(selected_features)

['genres', 'keywords', 'original_language', 'tagline', 'cast', 'director']


In [8]:
#replacing the missing values with null string
for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

In [9]:
#joining the all 5 rows
joined_features = movies_data['genres']+' ' +movies_data['keywords']+' '+movies_data['original_language']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']
print(joined_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  en A newlywed couple's honeymo...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      en A New Yorker in Shanghai Daniel Henney El...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [10]:
#coverting the txt data in to feature vectors
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(joined_features)

In [11]:
#getting similarity score by using cosine similarity
similarity = cosine_similarity(feature_vectors)
print(similarity,"\n")
print(similarity.shape)

[[1.         0.0731602  0.03890829 ... 0.0012222  0.00126498 0.0011916 ]
 [0.0731602  1.         0.03384574 ... 0.0367837  0.00110423 0.00104018]
 [0.03890829 0.03384574 1.         ... 0.00125046 0.05512248 0.00121915]
 ...
 [0.0012222  0.0367837  0.00125046 ... 1.         0.00129619 0.02770363]
 [0.00126498 0.00110423 0.05512248 ... 0.00129619 1.         0.00126374]
 [0.0011916  0.00104018 0.00121915 ... 0.02770363 0.00126374 1.        ]] 

(4803, 4803)


Getting the movie name from user

In [12]:
#getting the name of the movie from the user
name_of_the_movie = input("Enter your favourite name of the movie:")

Enter your favourite name of the movie:Batman


In [13]:
#creating a list that contains all the name f the movie in tha given data set
all_titles = movies_data["title"].tolist()
print(all_titles)

['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [14]:
#finding the closest match for a name of the movie given by the user
close_match = difflib.get_close_matches(name_of_the_movie,all_titles)
print(close_match)
close_movie = close_match[0]
print(close_movie)

['Batman', 'Batman', 'Catwoman']
Batman


In [15]:
#find the index of the movie with the tittle given by the user
index_of_the_movie = movies_data[movies_data.title == close_movie]["index"].values[0]
print(index_of_the_movie)

1359


In [16]:
#getting a similar score
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score,"\n")
len(similarity_score)

[(0, 0.0263445220295328), (1, 0.05070907996440225), (2, 0.014665799858408867), (3, 0.20531950588967338), (4, 0.025932606043718387), (5, 0.11629662207915725), (6, 0.0010691647294710793), (7, 0.006582225156871608), (8, 0.03199179322910504), (9, 0.09070938097465625), (10, 0.11345908313980743), (11, 0.012735433236808357), (12, 0.03929567136777334), (13, 0.0142247101279537), (14, 0.12906434943515033), (15, 0.01143079887147043), (16, 0.006241731275180398), (17, 0.017031903325501876), (18, 0.04250606970475927), (19, 0.030575253941986756), (20, 0.0262353104987436), (21, 0.0054738457782347654), (22, 0.018859814989127338), (23, 0.02576127208599202), (24, 0.04282031927562191), (25, 0.001063552495534258), (26, 0.006793159671786786), (27, 0.014056424867647566), (28, 0.01543081356119155), (29, 0.006822544778566485), (30, 0.11430511580352411), (31, 0.023917314321737305), (32, 0.09082886387823641), (33, 0.006541377055136622), (34, 0.001071365308628508), (35, 0.02687571933011564), (36, 0.04419878443800

4803

In [17]:
#based on their similarity score for sorting the movies
similarity_score_sorted = sorted(similarity_score,key = lambda x:x[1],reverse = True)
print(similarity_score_sorted)

[(1359, 1.0), (428, 0.4317912675506331), (210, 0.2581282364909296), (3, 0.20531950588967338), (119, 0.19351951383602314), (65, 0.17844209512916542), (1512, 0.14788984672028443), (813, 0.14499889167950344), (2530, 0.13826015699546584), (1017, 0.1378551003944517), (753, 0.13308079917066548), (473, 0.13308003188685613), (278, 0.1307708827185515), (14, 0.12906434943515033), (72, 0.12356442621136482), (2313, 0.11933201446483369), (2381, 0.11833408973093204), (5, 0.11629662207915725), (2858, 0.11514062370437668), (30, 0.11430511580352411), (4183, 0.11424818125579309), (2655, 0.11370602528684912), (10, 0.11345908313980743), (1035, 0.11292915404749483), (2685, 0.1106381131453785), (870, 0.10814834024668021), (41, 0.1074104100268703), (1296, 0.1065918488611859), (438, 0.10381403087624534), (1477, 0.10278915481813009), (299, 0.10252010010378497), (1474, 0.101814185795469), (1002, 0.10152594001045623), (1085, 0.1010231739638991), (2753, 0.10046641308936033), (303, 0.09979873678697317), (2805, 0.0

In [18]:
#based on their idex to print the name of similar movies
print("movies suggested for you:")
i = 1
for movie in similarity_score_sorted:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]["title"].values[0]
  if i<31:
    print(i,'.',title_from_index)
    i = i+1

movies suggested for you:
1 . Batman
2 . Batman Returns
3 . Batman & Robin
4 . The Dark Knight Rises
5 . Batman Begins
6 . The Dark Knight
7 . A History of Violence
8 . Superman
9 . Beetlejuice
10 . Bedazzled
11 . The Sentinel
12 . Mars Attacks!
13 . Planet of the Apes
14 . Man of Steel
15 . Suicide Squad
16 . The Mask
17 . Salton Sea
18 . Spider-Man 3
19 . The Postman Always Rings Twice
20 . Spider-Man 2
21 . Hang 'em High
22 . Dungeons & Dragons: Wrath of the Dragon God
23 . Superman Returns
24 . Jonah Hex
25 . Exorcist II: The Heretic
26 . Superman II
27 . Green Lantern
28 . Superman III
29 . Something's Gotta Give
30 . Reds


Movie Recommendation

In [19]:
name_of_the_movie = input("Enter your favourite name of the movie:")
all_titles = movies_data["title"].tolist()
close_match = difflib.get_close_matches(name_of_the_movie,all_titles)
close_movie = close_match[0]
index_of_the_movie = movies_data[movies_data.title == close_movie]["index"].values[0]
similarity_score = list(enumerate(similarity[index_of_the_movie]))
similarity_score_sorted = sorted(similarity_score,key = lambda x:x[1],reverse = True)
print("movies suggested for you:")
i = 1
for movie in similarity_score_sorted:
  index = movie[0]
  title_from_index = movies_data[movies_data.index == index]["title"].values[0]
  if i<31:
    print(i,'.',title_from_index)
    i = i+1

Enter your favourite name of the movie:Ironman
movies suggested for you:
1 . Iron Man
2 . Iron Man 2
3 . Iron Man 3
4 . Avengers: Age of Ultron
5 . The Avengers
6 . Captain America: Civil War
7 . Captain America: The Winter Soldier
8 . Ant-Man
9 . X-Men
10 . Made
11 . X-Men: Apocalypse
12 . X2
13 . The Helix... Loaded
14 . The Incredible Hulk
15 . X-Men: First Class
16 . X-Men: Days of Future Past
17 . Captain America: The First Avenger
18 . Kick-Ass 2
19 . Guardians of the Galaxy
20 . Deadpool
21 . Thor: The Dark World
22 . G-Force
23 . X-Men: The Last Stand
24 . Duets
25 . Mortdecai
26 . The Last Airbender
27 . Southland Tales
28 . Zathura: A Space Adventure
29 . Sky Captain and the World of Tomorrow
30 . The Amazing Spider-Man 2
